# Generated by Django 3.0.3 on 2020-02-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrad_graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='irradgraphinputs',
            name='image',
            field=models.ImageField(default='empty.png', upload_to='irrad_graph'),
        ),
    ]
