# Generated by Django 3.0.3 on 2020-02-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrad_graph', '0003_auto_20200228_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irradgraphinputs',
            name='image',
            field=models.ImageField(default='empty.png', upload_to='irrad_graph'),
        ),
    ]
