# Generated by Django 4.0.5 on 2022-06-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrad_graph', '0007_rename_irradgraphinputs_irradgraph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irradgraph',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='irrad_graph'),
        ),
    ]
