# Generated by Django 4.0.5 on 2022-06-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrad_graph', '0008_alter_irradgraph_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='irradgraph',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
