# Generated by Django 3.0.3 on 2020-02-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrad_graph', '0002_irradgraphinputs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irradgraphinputs',
            name='image',
            field=models.ImageField(null=True, upload_to='irrad_graph'),
        ),
    ]
