# Generated by Django 4.0.5 on 2022-06-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irrad_graph', '0005_auto_20200228_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irradgraphinputs',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='irradgraphinputs',
            old_name='longitude',
            new_name='long',
        ),
    ]
