# Generated by Django 4.0.5 on 2022-06-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrad_graph', '0009_irradgraph_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='irradgraph',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='media/csv'),
        ),
        migrations.AlterField(
            model_name='irradgraph',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/graph_imgs'),
        ),
    ]
